<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI5SyrdW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI5SyrdW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI5SyrdW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI5SyrdW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI5SyrdW\App_KernelDevDebugContainer([
    'container.build_hash' => 'I5SyrdW',
    'container.build_id' => '20dbe51d',
    'container.build_time' => 1648258603,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI5SyrdW');
