<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/main']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\MainController::home'], [], [['text', '/']], [], [], []],
    'custom' => [['name'], ['name' => null, '_controller' => 'App\\Controller\\MainController::custom'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/custom']], [], [], []],
    'post.index' => [[], ['_controller' => 'App\\Controller\\PostController::index'], [], [['text', '/post/']], [], [], []],
    'post.create' => [[], ['_controller' => 'App\\Controller\\PostController::create'], [], [['text', '/post/create']], [], [], []],
    'post.show' => [['id'], ['_controller' => 'App\\Controller\\PostController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/show']], [], [], []],
    'post.delete' => [['id'], ['_controller' => 'App\\Controller\\PostController::remove'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/post/delete']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
